version: '3'

services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    command: --wiredTigerCacheSizeGB 0.25

  client:
    build: ./client
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    restart: always

  server:
    build: ./server
    expose:
      - '3001'
    ports:
      - '3001:3001'
    volumes:
      - /app/node_modules
      - ./server:/app
    restart: always
    depends_on:
      - mongo

volumes:
  mongodb: